dashboard/config/routes.rb
Rails.application.routes.draw do
  get 'main/hud'

  root 'main#hud'

  resources :indicators
  resources :plots
  resources :plot_families

end

dashboard/app/controllers/main_controller.rb
class MainController < ApplicationController
  def hud
    @plot_family = PlotFamily.all.first
  end
end

dashboard/app/helpers/main_helper.rb
module MainHelper
end

dashboard/app/views/main/hud.html.erb
<meta http-equiv="refresh" content="<%= (@plot_family.refresh_int_mins * 60).to_i %>" />
<h1>Behold, ye dashboard
</h1>

<h3>Ye largest price changes</h3>
<% PriceDeltaCategory.all.each{ |pdc| %>
<b><%= pdc.title %></b><br>
	<% pdc.delta_samples.each{ |ds| %>
		<% if ds.value > 0 %> 
			<font color='green'>
		<% else %>
			<font color='red'>
		<% end %>
		<a href="https://www.google.com/finance?cid=<%= ds.indicator.uri %>"><%= ds.indicator.name %></a>: <%= (ds.value * 100).round(3) %>%</font>
	<% } %>
<br>
<% } %>
<br>

<h3>Ye technical indicators</h3>
<% TechnicalEvent.all.order(:stamp).each{ |te| %>
  <%= te.name %> at <%= te.stamp %> for <a href='indicators/<%= te.indicator_id %>'><%= te.indicator.name %></a>; 
<% } %>
<br>

<% if @plot_family %>
<%= render "shared/plot_family" %>
<% end %>
<br><br>
Edit:<br>
<%= link_to 'New Plots Family', new_plot_family_path %>&nbsp;<%= link_to 'Manage Plots Families', plot_families_path %><br>
<%= link_to 'New Plot', new_plot_path %>&nbsp;<%= link_to 'Manage Plot', plots_path %><br>
<%= link_to 'New Indicator', new_indicator_path %>&nbsp;<%= link_to 'Manage Indicators', indicators_path %><br>