dashboard/config/routes.rb
Rails.application.routes.draw do
  get 'main/hud'

  root 'main#hud'

  resources :indicators
  resources :plots
  resources :plot_families

end

dashboard/app/models/plot_family.rb
class PlotFamily < ActiveRecord::Base
  has_many :plot_to_families
  has_many :plots, through: :plot_to_families
end

dashboard/app/controllers/plot_families_controller.rb
class PlotFamiliesController < ApplicationController
  def new
    @plot_family = PlotFamily.new
  end

  def create
    @plot_family = PlotFamily.new(params.require(:plot_family).permit(:name, :refresh_int_mins))
    @plot_family.save

    @plots = params[:plots]
    @plots.each { |i|
      s = PlotToFamily.new(:plot_id => i.to_i, :plot_family_id => @plot_family.id)
      s.save
    }
    redirect_to @plot_family
  end

  def show
    @plot_family = PlotFamily.find(params[:id])
  end

  def edit
    @plot_family = PlotFamily.find(params[:id])
  end

  def update
    @plot_family = PlotFamily.find(params[:id])
    @plot_family.update(params.require(:plot_family).permit(:name, :refresh_int_mins))
    @plot_family.plot_to_families.destroy_all

    @plots = params[:plots]
    @plots.each { |i|
      p = PlotToFamily.new(:plot_id => i.to_i, :plot_family_id => @plot_family.id)
      p.save
    }

    redirect_to @plot_family
  end

  def index
    @plot_families = PlotFamily.all
  end

  def destroy
   @plot_family = PlotFamily.find(params[:id])
   @plot_family.destroy

   redirect_to plot_families_path
  end
end

dashboard/app/helpers/plot_families_helper.rb
module PlotFamiliesHelper
end

dashboard/app/views/plot_families/edit.html.erb
<h1>Edit Plot Family</h1>
<%= form_for(@plot_family) do |p| %>
<%= p.label :name %><br>
<%= p.text_field :name %><br><br>
<%= p.label :refresh_int_mins %><br>
<%= p.text_field :refresh_int_mins %><br><br>

<% curr_inds = [] %>
<% @plot_family.plots.each { |i| %>
  <% curr_inds << i.id %>
<% } %>

<%= select_tag "plots",
	options_from_collection_for_select(Plot.all, 'id', 'name', curr_inds),
	{ :multiple => true, :size => 10} %>
<%= p.submit %>
<% end %>

dashboard/app/views/plot_families/index.html.erb
<h1>Listing Plot Families</h1>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  <% @plot_families.each do |plot| %>
    <tr>
      <td><%= plot.name %></td>
      <td><%= link_to 'Show', plot_family_path(plot) %></td>
      <td><%= link_to 'Edit', edit_plot_family_path(plot) %></td>
      <td><%= link_to 'Destroy', plot_family_path(plot), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

dashboard/app/views/plot_families/new.html.erb
<h1>New Plot Family!</h1>
<%= form_for :plot_family, url: plot_families_path do |p| %>
<%= p.label :name %><br>
<%= p.text_field :name %><br><br>
<%= p.label :refresh_int_mins %><br>
<%= p.text_field :refresh_int_mins %><br><br>
<%= select_tag "plots",
	options_from_collection_for_select(Plot.all, 'id', 'name'),
	{ :multiple => true, :size => 10} %>
<%= p.submit %>
<% end %>

dashboard/app/views/plot_families/show.html.erb
<p>
<strong>Name: </strong>
<%= @plot_family.name %>
</p>
<%= render "shared/plot_family" %>