dashboard/config/routes.rb
Rails.application.routes.draw do
  get 'main/hud'

  root 'main#hud'

  resources :indicators
  resources :plots
  resources :plot_families

end

dashboard/app/models/plot.rb
class Plot < ActiveRecord::Base
  has_many :series
  has_many :indicators, through: :series
  has_many :plot_to_families
  has_many :plot_families, through: :plot_to_families
  
  def regenerate_series
    series_str = ""
	
	first = true
    self.indicators.each{ |i|
      if first
        first = false
      else
        series_str << ","
	  end
      series_str << "{\n"
      series_str << "name: '#{i.name}',\n" 
      series_str << "data: [\n"
      i.datapoints.order(:day).each{ |dp|
	    if Date.today - dp.day <= self.days_duration
          series_str << "[Date.UTC(#{dp.day.year},#{dp.day.mon - 1},#{dp.day.mday}),#{dp.value}],\n"
	    end
      }
      series_str << "]\n"
      series_str << "}\n"
    }
  
	self.dataset = series_str.html_safe
	self.save
  end
end

dashboard/app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  def new
    @plot = Plot.new
  end

  def create
    @plot = Plot.new(params.require(:plot).permit(:name, :days_duration))
    @plot.save

    @indicators = params[:indicators]
    @indicators.each { |i|
      s = Series.new(:indicator_id => i.to_i, :plot_id => @plot.id)
      s.save
    }
	@plot.regenerate_series
    redirect_to @plot
  end

  def show
    @plot = Plot.find(params[:id])
  end

  def edit
    @plot = Plot.find(params[:id])
  end

  def update
    @plot = Plot.find(params[:id])
    @plot.update(params.require(:plot).permit(:name, :days_duration))
    @plot.series.destroy_all

    @indicators = params[:indicators]
    @indicators.each { |i|
      s = Series.new(:indicator_id => i.to_i, :plot_id => @plot.id)
      s.save
    }
	@plot.regenerate_series
    redirect_to @plot
  end

  def index
    @plots = Plot.all
  end

  def destroy
   @plot = Plot.find(params[:id])
   @plot.series.destroy_all
   @plot.plot_to_families.destroy_all
   @plot.destroy

   redirect_to plots_path
  end
end

dashboard/app/helpers/plots_helper.rb
module PlotsHelper
end

dashboard/app/views/plots/edit.html.erb
<h1>Edit plot</h1>
<%= form_for(@plot) do |p| %>
<%= p.label :name %><br>
<%= p.text_field :name %><br><br>
<%= p.label :days_duration %><br>
<%= p.text_field :days_duration %><br><br>

<% curr_inds = [] %>
<% @plot.indicators.each { |i| %>
  <% curr_inds << i.id %>
<% } %>

<%= select_tag "indicators",
	options_from_collection_for_select(Indicator.all, 'id', 'name', curr_inds),
	{ :multiple => true, :size => 10} %>
<%= p.submit %>
<% end %>

dashboard/app/views/plots/index.html.erb
<h1>Listing Plots</h1>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  <% @plots.each do |plot| %>
    <tr>
      <td><%= plot.name %></td>
      <td><%= link_to 'Show', plot_path(plot) %></td>
      <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
      <td><%= link_to 'Destroy', plot_path(plot), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

dashboard/app/views/plots/new.html.erb
<h1>New Plot!</h1>
<%= form_for :plot, url: plots_path do |p| %>
<%= p.label :name %><br>
<%= p.text_field :name %><br><br>
<%= p.label :days_duration %><br>
<%= p.text_field :days_duration %><br><br>
<%= select_tag "indicators",
	options_from_collection_for_select(Indicator.all, 'id', 'name'),
	{ :multiple => true, :size => 10} %>
<%= p.submit %>
<% end %>

dashboard/app/views/plots/show.html.erb
<p>
<strong>Name: </strong>
<%= @plot.name %>
</p>
<% @next_plot = @plot %>
<%= render "shared/plot" %>