dashboard/config/routes.rb
Rails.application.routes.draw do
  get 'main/hud'

  root 'main#hud'

  resources :indicators
  resources :plots
  resources :plot_families

end

dashboard/app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :datapoints, dependent: :destroy
  has_many :series
  has_many :plots, through: :series
  has_many :average_samples
  has_many :technical_events
end

dashboard/app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  def new
    @indicator = Indicator.new
  end

  def create
    @indicator = Indicator.new(params.require(:indicator).permit(:name, :uri))
    #if not @indicator.uri.include? "http"
    #  @indicator.uri = "http://www.google.com/finance/historical?cid=#{@indicator.uri}&startdate=Sep+10%2C+1975&num=25000&output=csv"
    #end
    @indicator.save
    redirect_to @indicator
  end

  def show
    @indicator = Indicator.find(params[:id])
  end

  def index
    @indicators = Indicator.all
  end

  def destroy
   @indicator = Indicator.find(params[:id])
   @indicator.destroy

   redirect_to indicators_path
  end
end

dashboard/app/helpers/indicators_helper.rb
module IndicatorsHelper
end

dashboard/app/views/indicators/index.html.erb
<h1>Listing Indicators</h1>
<table>
  <tr>
    <th>Name</th>
    <th>URI</th>
    <th colspan="2"></th>
  </tr>
  <% @indicators.each do |indicator| %>
    <tr>
      <td><%= indicator.name %></td>
      <td><%= indicator.uri %></td>
      <td><%= link_to 'Show', indicator_path(indicator) %></td>
      <td><%= link_to 'Destroy', indicator_path(indicator), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

dashboard/app/views/indicators/new.html.erb
<h1>New Indicator!</h1>
<%= form_for :indicator, url: indicators_path do |i| %>
<%= i.label :name %><br>
<%= i.text_field :name %><br><br>
<%= i.label :uri %><br>
<%= i.text_field :uri %><br><br>
<%= i.submit %>
<% end %>

dashboard/app/views/indicators/show.html.erb
<p>
<strong>Name: </strong>
<%= @indicator.name %>
</p>
<%= render "shared/indicator_plot" %>
<p>
<strong>URI: </strong>
<%= @indicator.uri %>
</p>
<% @indicator.datapoints.order(day: :desc).each { |dp| %>
<%= dp.day %>:<%= dp.value %><br>
<% } %>